name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install dependencies
        # We need to remove glib-network, otherwise libproxy might cause crashes.
        run: |
          sudo apt --yes purge glib-networking
          sudo apt --yes --purge autoremove
          sudo apt update || true
          sudo apt --yes --no-install-recommends install libglib2.0-dev libbson-dev libleveldb-dev liblmdb-dev libmongoc-dev libsqlite3-dev librados-dev libfuse-dev libmariadb-dev librocksdb-dev
          sudo apt --yes --no-install-recommends install python3 python3-pip python3-setuptools python3-wheel ninja-build
          sudo pip3 install meson
      - name: Configure
        env:
          CC: ${{ matrix.compiler }}
        run: |
          meson setup --prefix="${GITHUB_WORKSPACE}/julea-install" --buildtype=release --werror bld
      - name: Build
        run: |
          ninja -C bld
      - name: Install
        run: |
          ninja -C bld install
